### PR TITLE
Fixes for default parameters

### LINKED ISSUE #31: Improve default parameter hiding
Currently, parameters with name starting with `qos_overrides./` and `use_sim_time` are hidden. Apparently, ROS iron added `start_type_description_service`, which should be added to the list. Maybe a toggle to show all those parameters would also be useful

### PR DESCRIPTION
**Pull request by ottojo**
* Add `start_type_description_service` default parameter
* Add toggle to show/hide default parameters

fixes #31

### CODE REVIEW

File: src/service_wrapper.cpp [hunk 1]
```diff
@@ -285,3 +288,7 @@ void ServiceWrapper::parameterModificationResponseReceived(const rclcpp::Client<
 
     responseQueue.push(response);
 }
+
+void ServiceWrapper::setIgnoreDefaultParameters(bool ignoreDefaultParameters_) {
+    this->ignoreDefaultParameters=ignoreDefaultParameters_;
```
Comment (authaldo) [inline src/service_wrapper.cpp:293]:
```suggestion
    this->ignoreDefaultParameters = ignoreDefaultParameters_;
```
small personal preference :D

**Review by authaldo — APPROVED** [review]
LGTM, thanks!
